[{"name": "test.test_session.HijackTest.test_session1", "status": "failed", "message": "None != 34", "passed": false, "points": ["2.7.1", "2.7.2", "2.7.3", "2.7.4", "2.7.5"], "backtrace": ["  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\yaoxuemeng\\AppData\\Local\\tmc\\tmc_cli_rust\\mooc-securing-software-25\\part2-13.sessionhijack\\test\\test_session.py\", line 37, in test_session1\n    self.perform_test(0, 10)\n", "  File \"C:\\Users\\yaoxuemeng\\AppData\\Local\\tmc\\tmc_cli_rust\\mooc-securing-software-25\\part2-13.sessionhijack\\test\\test_session.py\", line 34, in perform_test\n    self.assertEqual(test_session(self.live_server_url), balance)\n"]}, {"name": "Loader", "status": "errored", "message": "[Errno 22] Invalid argument", "passed": false, "points": [], "backtrace": ["  File \"C:\\Users\\yaoxuemeng\\AppData\\Local\\tmc\\tmc_cli_rust\\mooc-securing-software-25\\part2-13.sessionhijack\\tmc\\__main__.py\", line 25, in <module>\n    failures = test_runner.run_tests([\"test\"])\n", "  File \"D:\\py3.10\\lib\\site-packages\\django\\test\\runner.py\", line 1099, in run_tests\n    result = self.run_suite(suite)\n", "  File \"D:\\py3.10\\lib\\site-packages\\django\\test\\runner.py\", line 1026, in run_suite\n    return runner.run(suite)\n", "  File \"C:\\Users\\yaoxuemeng\\AppData\\Local\\tmc\\tmc_cli_rust\\mooc-securing-software-25\\part2-13.sessionhijack\\tmc\\runner.py\", line 19, in run\n    return super(TMCTestRunner, self).run(test)\n", "  File \"D:\\py3.10\\lib\\unittest\\runner.py\", line 184, in run\n    test(result)\n", "  File \"D:\\py3.10\\lib\\unittest\\suite.py\", line 84, in __call__\n    return self.run(*args, **kwds)\n", "  File \"D:\\py3.10\\lib\\unittest\\suite.py\", line 122, in run\n    test(result)\n", "  File \"D:\\py3.10\\lib\\site-packages\\django\\test\\testcases.py\", line 321, in __call__\n    self._setup_and_call(result)\n", "  File \"D:\\py3.10\\lib\\site-packages\\django\\test\\testcases.py\", line 376, in _setup_and_call\n    super().__call__(result)\n", "  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 650, in __call__\n    return self.run(*args, **kwds)\n", "  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 599, in run\n    self._feedErrorsToResult(result, outcome.errors)\n", "  File \"D:\\py3.10\\lib\\unittest\\case.py\", line 516, in _feedErrorsToResult\n    result.addFailure(test, exc_info)\n", "  File \"C:\\Users\\yaoxuemeng\\AppData\\Local\\tmc\\tmc_cli_rust\\mooc-securing-software-25\\part2-13.sessionhijack\\tmc\\result.py\", line 23, in addFailure\n    super(TMCResult, self).addFailure(test, err)\n", "  File \"D:\\py3.10\\lib\\unittest\\runner.py\", line 83, in addFailure\n    self.stream.flush()\n"]}]